const translations = {
    'pt-BR': {
        'page-title': 'Mesa de Taverna',
        'main-title': 'Mesa de Taverna',
        'intro-desc': 'Bem-vindo à Mesa de Taverna, aventureiro! Desafie a sorte com dados e cartas em jogos de pura bravura!',
        'tutorial-link': 'Ver Tutorial dos Jogos',
        'game1-title': 'Jogo 1: Rolar Dados',
        'game1-desc': 'Jogue dois dados e veja a soma, como os bardos contam suas façanhas!',
        'game1-sum-label': 'Soma: ',
        'game2-title': 'Jogo 2: Maior ou Menor',
        'game2-desc': 'Aposte se a soma dos dados será maior ou menor que 7.',
        'game2-sum-label': 'Soma: ',
        'game3-title': 'Jogo 3: Par ou Ímpar',
        'game3-desc': 'Aposte se a soma dos dados será par ou ímpar.',
        'game3-sum-label': 'Soma: ',
        'game4-title': 'Jogo 4: Aposta na Soma Exata',
        'game4-desc': 'Escolha a soma exata dos dois dados (2 a 12).',
        'game5-title': 'Jogo 5: Três ou Nada',
        'game5-desc': 'Aposte se a soma de três dados será divisível por 3.',
        'game5-sum-label': 'Soma: ',
        'game6-title': 'Jogo 6: Vinte e Um',
        'game6-desc': 'Tente chegar a 21 sem ultrapassar, contra o mestre da taverna.',
        'game6-score-label': 'Pontuação: ',
        'game7-title': 'Jogo 7: Maior Carta',
        'game7-desc': 'Compare sua carta com a do mestre (Ás a Rei).',
        'game8-title': 'Jogo 8: Par Perfeito',
        'game8-desc': 'Aposte se duas cartas formarão um par.',
        'game9-title': 'Jogo 9: Soma 13',
        'game9-desc': 'Tente somar exatamente 13 com duas cartas.',
        'game9-sum-label': 'Soma: ',
        'game10-title': 'Jogo 10: Naipe Certo',
        'game10-desc': 'Adivinhe o naipe de uma carta.',
        'tut1-title': 'Rolar Dados',
        'tut1-desc': 'Role dois dados de 6 lados e veja a soma total. Não há apostas, apenas a emoção de rolar!',
        'tut2-title': 'Maior ou Menor',
        'tut2-desc': 'Escolha se a soma de dois dados será maior ou menor que 7. Se acertar, você vence!',
        'tut3-title': 'Par ou Ímpar',
        'tut3-desc': 'Aposte se a soma de dois dados será par ou ímpar. Teste sua intuição!',
        'tut4-title': 'Aposta na Soma Exata',
        'tut4-desc': 'Escolha um número de 2 a 12. Se a soma dos dois dados for exatamente esse número, você ganha!',
        'tut5-title': 'Três ou Nada',
        'tut5-desc': 'Role três dados. Se a soma for divisível por 3, você vence. Caso contrário, a taverna leva a melhor!',
        'tut6-title': 'Vinte e Um',
        'tut6-desc': 'Receba duas cartas e some seus valores (Ás=1, 2-10=valor, Valete/Dama/Rei=10). Tente chegar a 21 sem ultrapassar, competindo contra o mestre da taverna.',
        'tut7-title': 'Maior Carta',
        'tut7-desc': 'Receba uma carta e compare com a do mestre. A maior carta vence (Ás=1, 2-10=valor, Valete=11, Dama=12, Rei=13).',
        'tut8-title': 'Par Perfeito',
        'tut8-desc': 'Receba duas cartas. Se forem do mesmo valor (ex.: dois 5), você vence!',
        'tut9-title': 'Soma 13',
        'tut9-desc': 'Receba duas cartas e some seus valores (Ás=1, 2-10=valor, Valete/Dama/Rei=10). Se a soma for exatamente 13, você ganha!',
        'tut10-title': 'Naipe Certo',
        'tut10-desc': 'Escolha um naipe (Copas, Ouros, Espadas, Paus). Uma carta será revelada. Se o naipe for o escolhido, você vence!',
        'back-link': 'Voltar aos Jogos'
    },
    'en': {
        'page-title': 'Tavern Table',
        'main-title': 'Tavern Table',
        'intro-desc': 'Welcome to the Tavern Table, adventurer! Test your luck with dice and card games of pure bravery!',
        'tutorial-link': 'View Game Tutorial',
        'game1-title': 'Game 1: Roll Dice',
        'game1-desc': 'Roll two dice and see the sum, as bards tell their tales!',
        'game1-sum-label': 'Sum: ',
        'game2-title': 'Game 2: Higher or Lower',
        'game2-desc': 'Bet if the sum of two dice will be higher or lower than 7.',
        'game2-sum-label': 'Sum: ',
        'game3-title': 'Game 3: Odd or Even',
        'game3-desc': 'Bet if the sum of two dice will be odd or even.',
        'game3-sum-label': 'Sum: ',
        'game4-title': 'Game 4: Exact Sum Bet',
        'game4-desc': 'Choose the exact sum of two dice (2 to 12).',
        'game5-title': 'Game 5: Three or Nothing',
        'game5-desc': 'Bet if the sum of three dice will be divisible by 3.',
        'game5-sum-label': 'Sum: ',
        'game6-title': 'Game 6: Twenty-One',
        'game6-desc': 'Try to reach 21 without going over, against the tavern master.',
        'game6-score-label': 'Score: ',
        'game7-title': 'Game 7: Higher Card',
        'game7-desc': 'Compare your card with the master’s (Ace to King).',
        'game8-title': 'Game 8: Perfect Pair',
        'game8-desc': 'Bet if two cards will form a pair.',
        'game9-title': 'Game 9: Sum 13',
        'game9-desc': 'Try to sum exactly 13 with two cards.',
        'game9-sum-label': 'Sum: ',
        'game10-title': 'Game 10: Suit Guess',
        'game10-desc': 'Guess the suit of a card.',
        'tut1-title': 'Roll Dice',
        'tut1-desc': 'Roll two 6-sided dice and see the total sum. No bets, just the thrill of rolling!',
        'tut2-title': 'Higher or Lower',
        'tut2-desc': 'Choose if the sum of two dice will be higher or lower than 7. If correct, you win!',
        'tut3-title': 'Odd or Even',
        'tut3-desc': 'Bet if the sum of two dice will be odd or even. Test your intuition!',
        'tut4-title': 'Exact Sum Bet',
        'tut4-desc': 'Choose a number from 2 to 12. If the sum of two dice matches it exactly, you win!',
        'tut5-title': 'Three or Nothing',
        'tut5-desc': 'Roll three dice. If the sum is divisible by 3, you win. Otherwise, the tavern wins!',
        'tut6-title': 'Twenty-One',
        'tut6-desc': 'Receive two cards and sum their values (Ace=1, 2-10=value, Jack/Queen/King=10). Try to reach 21 without going over, competing against the tavern master.',
        'tut7-title': 'Higher Card',
        'tut7-desc': 'Receive a card and compare it with the master’s. The highest card wins (Ace=1, 2-10=value, Jack=11, Queen=12, King=13).',
        'tut8-title': 'Perfect Pair',
        'tut8-desc': 'Receive two cards. If they have the same value (e.g., two 5s), you win!',
        'tut9-title': 'Sum 13',
        'tut9-desc': 'Receive two cards and sum their values (Ace=1, 2-10=value, Jack/Queen/King=10). If the sum is exactly 13, you win!',
        'tut10-title': 'Suit Guess',
        'tut10-desc': 'Choose a suit (Hearts, Diamonds, Spades, Clubs). A card is revealed. If the suit matches your choice, you win!',
        'back-link': 'Back to Games'
    },
    'es': {
        'page-title': 'Mesa de Taberna',
        'main-title': 'Mesa de Taberna',
        'intro-desc': '¡Bienvenido a la Mesa de Taberna, aventurero! ¡Desafía tu suerte con juegos de dados y cartas llenos de valentía!',
        'tutorial-link': 'Ver Tutorial de los Juegos',
        'game1-title': 'Juego 1: Tirar Dados',
        'game1-desc': 'Lanza dos dados y observa la suma, ¡como los bardos cuentan sus hazañas!',
        'game1-sum-label': 'Suma: ',
        'game2-title': 'Juego 2: Mayor o Menor',
        'game2-desc': 'Apuesta si la suma de dos dados será mayor o menor que 7.',
        'game2-sum-label': 'Suma: ',
        'game3-title': 'Juego 3: Par o Impar',
        'game3-desc': 'Apuesta si la suma de dos dados será par o impar.',
        'game3-sum-label': 'Suma: ',
        'game4-title': 'Juego 4: Apuesta a la Suma Exacta',
        'game4-desc': 'Elige la suma exacta de dos dados (2 a 12).',
        'game5-title': 'Juego 5: Tres o Nada',
        'game5-desc': 'Apuesta si la suma de tres dados será divisible por 3.',
        'game5-sum-label': 'Suma: ',
        'game6-title': 'Juego 6: Veintiuno',
        'game6-desc': 'Intenta llegar a 21 sin pasarte, contra el maestro de la taberna.',
        'game6-score-label': 'Puntuación: ',
        'game7-title': 'Juego 7: Carta Más Alta',
        'game7-desc': 'Compara tu carta con la del maestro (As a Rey).',
        'game8-title': 'Juego 8: Par Perfecto',
        'game8-desc': 'Apuesta si dos cartas formarán un par.',
        'game9-title': 'Juego 9: Suma 13',
        'game9-desc': 'Intenta sumar exactamente 13 con dos cartas.',
        'game9-sum-label': 'Suma: ',
        'game10-title': 'Juego 10: Adivina el Palo',
        'game10-desc': 'Adivina el palo de una carta.',
        'tut1-title': 'Tirar Dados',
        'tut1-desc': 'Lanza dos dados de 6 caras y observa la suma total. ¡Sin apuestas, solo la emoción de tirar!',
        'tut2-title': 'Mayor o Menor',
        'tut2-desc': 'Elige si la suma de dos dados será mayor o menor que 7. ¡Si aciertas, ganas!',
        'tut3-title': 'Par o Impar',
        'tut3-desc': 'Apuesta si la suma de dos dados será par o impar. ¡Prueba tu intuición!',
        'tut4-title': 'Apuesta a la Suma Exacta',
        'tut4-desc': 'Elige un número del 2 al 12. Si la suma de dos dados coincide exactamente, ¡ganas!',
        'tut5-title': 'Tres o Nada',
        'tut5-desc': 'Lanza tres dados. Si la suma es divisible por 3, ganas. ¡De lo contrario, la taberna gana!',
        'tut6-title': 'Veintiuno',
        'tut6-desc': 'Recibe dos cartas y suma sus valores (As=1, 2-10=valor, Jota/Reina/Rey=10). Intenta llegar a 21 sin pasarte, compitiendo contra el maestro de la taberna.',
        'tut7-title': 'Carta Más Alta',
        'tut7-desc': 'Recibe una carta y compárala con la del maestro. La carta más alta gana (As=1, 2-10=valor, Jota=11, Reina=12, Rey=13).',
        'tut8-title': 'Par Perfecto',
        'tut8-desc': 'Recibe dos cartas. Si tienen el mismo valor (ej.: dos 5), ¡ganas!',
        'tut9-title': 'Suma 13',
        'tut9-desc': 'Recibe dos cartas y suma sus valores (As=1, 2-10=valor, Jota/Reina/Rey=10). Si la suma es exactamente 13, ¡ganas!',
        'tut10-title': 'Adivina el Palo',
        'tut10-desc': 'Elige un palo (Corazones, Diamantes, Espadas, Tréboles). Se revela una carta. Si el palo coincide con tu elección, ¡ganas!',
        'back-link': 'Volver a los Juegos'
    }
};

function setLanguage() {
    const lang = navigator.language.split('-')[0] === 'es' ? 'es' : navigator.language === 'pt-BR' ? 'pt-BR' : 'en';
    document.querySelectorAll('[id]').forEach(element => {
        if (translations[lang][element.id]) {
            element.textContent = translations[lang][element.id];
        }
    });
    document.querySelectorAll('option').forEach((option, index) => {
        if (element.id === 'bet') {
            option.textContent = translations[lang][`bet-option-${index + 1}`] || option.textContent;
        } else if (element.id === 'parity-bet') {
            option.textContent = translations[lang][`parity-option-${index + 1}`] || option.textContent;
        } else if (element.id === 'suit-bet') {
            option.textContent = translations[lang][`suit-option-${index + 1}`] || option.textContent;
        }
    });
}

document.addEventListener('DOMContentLoaded', setLanguage);
