const translations = {
    'pt-BR': {
        // Interface Geral
        'page-title': 'Mesa de Taverna',
        'main-title': 'Mesa de Taverna',
        'intro-desc': 'Bem-vindo à Mesa de Taverna, aventureiro! Desafie a sorte com dados e cartas em jogos de pura bravura!',
        'coins-label': 'Moedas',
        'level-label': 'Nível',
        'tavern-notice-text': 'Nossos pedreiros são trolls bêbados, então esperem algumas instabilidades. No mais, protejam-se e tenham uma boa estadia!',
        'moedas': 'moedas',
        'win-message': 'Você venceu! Parabéns, aventureiro!',
        'lose-message': 'Você perdeu... Tente novamente!',
        'tie-message': 'Empate! A sorte está equilibrada.',
        'sum-label': 'Soma',
        'invalid-bet-message': 'Aposta inválida! Escolha um número entre 2 e 12.',
        'invalid-quantity-message': 'Quantidade inválida! Escolha entre 1 e 5 dados.',
        'player-label': 'Jogador',
        'dealer-label': 'Mestre',
        'bust-message': 'Estourou! Você passou de 21.',
        'dealer-bust': 'O mestre estourou! Você venceu!',
        // Títulos de Nível
        'Forasteiro': 'Forasteiro',
        'Viajante': 'Viajante',
        'Mercenário': 'Mercenário',
        'Aventureiro': 'Aventureiro',
        'Cavaleiro': 'Cavaleiro',
        'Senhor': 'Senhor',
        'Mestre': 'Mestre',
        // Conquistas
        'Aprendiz da Taverna': 'Aprendiz da Taverna',
        'Senhor dos Dados': 'Senhor dos Dados',
        'Rei do Vinte e Um': 'Rei do Vinte e Um',
        'Mestre da Moeda': 'Mestre da Moeda',
        'Profeta dos Dados': 'Profeta dos Dados',
        'Mestre dos Pares': 'Mestre dos Pares',
        'Jogue todos os jogos pelo menos uma vez': 'Jogue todos os jogos pelo menos uma vez',
        'Ganhe 20 vezes em jogos de dados': 'Ganhe 20 vezes em jogos de dados',
        'Ganhe 5 vezes em Vinte e Um': 'Ganhe 5 vezes em Vinte e Um',
        'Ganhe 10 vezes em Cara ou Coroa': 'Ganhe 10 vezes em Cara ou Coroa',
        'Ganhe 5 vezes em Maior ou Menor': 'Ganhe 5 vezes em Maior ou Menor',
        'Ganhe 3 vezes em Par Perfeito': 'Ganhe 3 vezes em Par Perfeito',
        // Jogos
        'game0-title': 'Cara ou Coroa',
        'game0-desc': 'Aposte se a moeda será cara ou coroa.',
        'game1-title': 'Rolar Dados',
        'game1-desc': 'Jogue dois dados e veja a soma, como os bardos contam suas façanhas!',
        'game2-title': 'Maior ou Menor',
        'game2-desc': 'Aposte se a soma dos dados será maior ou menor que 7.',
        'game3-title': 'Par ou Ímpar',
        'game3-desc': 'Aposte se a soma dos dados será par ou ímpar.',
        'game4-title': 'Aposta na Soma Exata',
        'game4-desc': 'Escolha a soma exata dos dois dados (2 a 12).',
        'game5-title': 'Três ou Nada',
        'game5-desc': 'Aposte se a soma de três dados será divisível por 3.',
        'game6-title': 'Vinte e Um',
        'game6-desc': 'Tente chegar a 21 sem ultrapassar, contra o mestre da taverna.',
        'game7-title': 'Maior Carta',
        'game7-desc': 'Compare sua carta com a do mestre (Ás a Rei).',
        'game8-title': 'Par Perfeito',
        'game8-desc': 'Aposte se duas cartas formarão um par.',
        'game9-title': 'Soma 13',
        'game9-desc': 'Tente somar exatamente 13 com duas cartas.',
        'game10-title': 'Naipe Certo',
        'game10-desc': 'Adivinhe o naipe de uma carta.',
        'game11-title': 'Rolador de Dados',
        'game11-desc': 'Escolha o tipo e a quantidade de dados e role-os como um verdadeiro aventureiro!',
        // Tutorial
        'gamification-tut-title': 'Gamificação',
        'gamification-tut-desc': 'Ganhe moedas por vitórias (10 moedas) ou derrotas (2 moedas), desbloqueie conquistas como "Senhor dos Dados", e suba de nível como aventureiro, de "Forasteiro" a "Mestre".',
        'dados-tut-title': 'Jogos de Dados',
        'cartas-tut-title': 'Jogos de Cartas',
        'passatempos-tut-title': 'Passatempos',
        'tut0-title': 'Cara ou Coroa',
        'tut0-desc': 'Escolha entre cara ou coroa e lance a moeda. Se acertar, você vence!',
        'tut1-title': 'Rolar Dados',
        'tut1-desc': 'Role dois dados de 6 lados e veja a soma total. Não há apostas, apenas a emoção de rolar!',
        'tut2-title': 'Maior ou Menor',
        'tut2-desc': 'Escolha se a soma de dois dados será maior ou menor que 7. Se acertar, você vence!',
        'tut3-title': 'Par ou Ímpar',
        'tut3-desc': 'Aposte se a soma dos dados será par ou ímpar. Teste sua intuição!',
        'tut4-title': 'Aposta na Soma Exata',
        'tut4-desc': 'Escolha um número de 2 a 12. Se a soma dos dois dados for exatamente esse número, você ganha!',
        'tut5-title': 'Três ou Nada',
        'tut5-desc': 'Role três dados. Se a soma for divisível por 3, você vence!',
        'tut6-title': 'Vinte e Um',
        'tut6-desc': 'Receba duas cartas, somando seus valores (Ás = 1 ou 11, 2-10 = valor, Valete/Dama/Rei = 10). Use "Comprar" para mais cartas ou "Passar" para parar. Tente chegar a 21 sem ultrapassar, contra o mestre da taverna, que compra até atingir 17 ou mais.',
        'tut7-title': 'Maior Carta',
        'tut7-desc': 'Receba uma carta e compare com a do mestre. A maior carta vence (Ás=1, 2-10=valor, Valete=11, Dama=12, Rei=13).',
        'tut8-title': 'Par Perfeito',
        'tut8-desc': 'Receba duas cartas. Se forem do mesmo valor (ex.: dois 5), você ganha!',
        'tut9-title': 'Soma 13',
        'tut9-desc': 'Receba duas cartas e some seus valores (Ás=1, 2-10=valor, Valete/Dama/Rei=10). Se a soma for exatamente 13, você ganha!',
        'tut10-title': 'Naipe Certo',
        'tut10-desc': 'Escolha um naipe (Copas, Ouros, Espadas, Paus). Uma carta será revelada. Se o naipe for o escolhido, você vence!',
        'tut11-title': 'Rolador de Dados',
        'tut11-desc': 'Escolha entre dados d4, d6, d8, d10, d12, ou d20, selecione a quantidade (1 a 5), e role para ver os resultados e a soma!',
        // Opções
        'cara': 'Cara',
        'coroa': 'Coroa',
        'maior': 'Mais que 7',
        'menor': 'Menos que 7',
        'par': 'Par',
        'impar': 'Ímpar',
        'copas': 'Copas',
        'ouros': 'Ouros',
        'espadas': 'Espadas',
        'paus': 'Paus'
    },
    'en-US': {
        // Interface Geral
        'page-title': 'Tavern Table',
        'main-title': 'Tavern Table',
        'intro-desc': 'Welcome to the Tavern Table, adventurer! Test your luck with dice and cards in games of pure bravery!',
        'coins-label': 'Coins',
        'level-label': 'Level',
        'tavern-notice-text': 'Our builders are drunken trolls, so expect some instability. Otherwise, stay safe and enjoy your stay!',
        'moedas': 'coins',
        'win-message': 'You won! Congratulations, adventurer!',
        'lose-message': 'You lost... Try again!',
        'tie-message': 'Tie! Luck is balanced.',
        'sum-label': 'Sum',
        'invalid-bet-message': 'Invalid bet! Choose a number between 2 and 12.',
        'invalid-quantity-message': 'Invalid quantity! Choose between 1 and 5 dice.',
        'player-label': 'Player',
        'dealer-label': 'Dealer',
        'bust-message': 'Bust! You went over 21.',
        'dealer-bust': 'The dealer busted! You win!',
        // Títulos de Nível
        'Forasteiro': 'Stranger',
        'Viajante': 'Traveler',
        'Mercenário': 'Mercenary',
        'Aventureiro': 'Adventurer',
        'Cavaleiro': 'Knight',
        'Senhor': 'Lord',
        'Mestre': 'Master',
        // Conquistas
        'Aprendiz da Taverna': 'Tavern Apprentice',
        'Senhor dos Dados': 'Lord of the Dice',
        'Rei do Vinte e Um': 'King of Blackjack',
        'Mestre da Moeda': 'Coin Master',
        'Profeta dos Dados': 'Dice Prophet',
        'Mestre dos Pares': 'Master of Pairs',
        'Jogue todos os jogos pelo menos uma vez': 'Play all games at least once',
        'Ganhe 20 vezes em jogos de dados': 'Win 20 times in dice games',
        'Ganhe 5 vezes em Vinte e Um': 'Win 5 times in Blackjack',
        'Ganhe 10 vezes em Cara ou Coroa': 'Win 10 times in Coin Toss',
        'Ganhe 5 vezes em Maior ou Menor': 'Win 5 times in Higher or Lower',
        'Ganhe 3 vezes em Par Perfeito': 'Win 3 times in Perfect Pair',
        // Jogos
        'game0-title': 'Coin Toss',
        'game0-desc': 'Bet on whether the coin will be heads or tails.',
        'game1-title': 'Roll Dice',
        'game1-desc': 'Roll two dice and see the sum, as bards tell their tales!',
        'game2-title': 'Higher or Lower',
        'game2-desc': 'Bet if the sum of the dice will be higher or lower than 7.',
        'game3-title': 'Odd or Even',
        'game3-desc': 'Bet if the sum of the dice will be odd or even.',
        'game4-title': 'Exact Sum Bet',
        'game4-desc': 'Choose the exact sum of two dice (2 to 12).',
        'game5-title': 'Three or Nothing',
        'game5-desc': 'Bet if the sum of three dice will be divisible by 3.',
        'game6-title': 'Blackjack',
        'game6-desc': 'Try to reach 21 without going over, against the tavern master.',
        'game7-title': 'Higher Card',
        'game7-desc': 'Compare your card with the master’s (Ace to King).',
        'game8-title': 'Perfect Pair',
        'game8-desc': 'Bet if two cards will form a pair.',
        'game9-title': 'Sum 13',
        'game9-desc': 'Try to sum exactly 13 with two cards.',
        'game10-title': 'Suit Guess',
        'game10-desc': 'Guess the suit of a card.',
        'game11-title': 'Dice Roller',
        'game11-desc': 'Choose the type and quantity of dice and roll them like a true adventurer!',
        // Tutorial
        'gamification-tut-title': 'Gamification',
        'gamification-tut-desc': 'Earn coins for wins (10 coins) or losses (2 coins), unlock achievements like "Lord of the Dice", and level up as an adventurer from "Stranger" to "Master".',
        'dados-tut-title': 'Dice Games',
        'cartas-tut-title': 'Card Games',
        'passatempos-tut-title': 'Pastimes',
        'tut0-title': 'Coin Toss',
        'tut0-desc': 'Choose heads or tails and flip the coin. If you guess right, you win!',
        'tut1-title': 'Roll Dice',
        'tut1-desc': 'Roll two 6-sided dice and see the total sum. No bets, just the thrill of rolling!',
        'tut2-title': 'Higher or Lower',
        'tut2-desc': 'Choose if the sum of two dice will be higher or lower than 7. If you guess right, you win!',
        'tut3-title': 'Odd or Even',
        'tut3-desc': 'Bet if the sum of the dice will be odd or even. Test your intuition!',
        'tut4-title': 'Exact Sum Bet',
        'tut4-desc': 'Choose a number from 2 to 12. If the sum of two dice is exactly that number, you win!',
        'tut5-title': 'Three or Nothing',
        'tut5-desc': 'Roll three dice. If the sum is divisible by 3, you win!',
        'tut6-title': 'Blackjack',
        'tut6-desc': 'Receive two cards, summing their values (Ace = 1 or 11, 2-10 = value, Jack/Queen/King = 10). Use "Hit" to draw more cards or "Stand" to stop. Try to reach 21 without going over, against the tavern master, who draws until reaching 17 or more.',
        'tut7-title': 'Higher Card',
        'tut7-desc': 'Receive a card and compare it with the master’s. The higher card wins (Ace=1, 2-10=value, Jack=11, Queen=12, King=13).',
        'tut8-title': 'Perfect Pair',
        'tut8-desc': 'Receive two cards. If they have the same value (e.g., two 5s), you win!',
        'tut9-title': 'Sum 13',
        'tut9-desc': 'Receive two cards and sum their values (Ace=1, 2-10=value, Jack/Queen/King=10). If the sum is exactly 13, you win!',
        'tut10-title': 'Suit Guess',
        'tut10-desc': 'Choose a suit (Hearts, Diamonds, Spades, Clubs). A card is revealed. If the suit matches your choice, you win!',
        'tut11-title': 'Dice Roller',
        'tut11-desc': 'Choose from d4, d6, d8, d10, d12, or d20 dice, select the quantity (1 to 5), and roll to see the results and sum!',
        // Opções
        'cara': 'Heads',
        'coroa': 'Tails',
        'maior': 'More than 7',
        'menor': 'Less than 7',
        'par': 'Even',
        'impar': 'Odd',
        'copas': 'Hearts',
        'ouros': 'Diamonds',
        'espadas': 'Spades',
        'paus': 'Clubs'
    }
};

function translate(key) {
    const lang = navigator.language || 'pt-BR';
    return translations[lang][key] || translations['pt-BR'][key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[id]').forEach(element => {
        const translation = translate(element.id);
        if (translation !== element.id) {
            element.textContent = translation;
        }
    });
    document.querySelectorAll('option').forEach(option => {
        const translation = translate(option.value);
        if (translation !== option.value) {
            option.textContent = translation;
        }
    });
}
